Fix Bazel website stardoc build (//site:site) after https://github.com/bazelbuild/bazel/commit/9c913b93e275038393e4ba5f67b7421919d93cf9
```
ERROR: /usr/local/google/home/jingwen/bazels/github/tools/build_defs/repo/BUILD:36:2: Generating Starlark doc for git_raw_md failed (Exit 1) stardoc failed: error executing command bazel-out/host/bin/external/io_bazel_skydoc/stardoc/stardoc '--input=//tools/build_defs/repo:git.bzl' '--output=bazel-out/k8-fastbuild/bin/tools/build_defs/repo/git_raw.md' '--workspace_name=io_bazel' ... (remaining 2 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Stardoc documentation generation failed: File tools/build_defs/repo/git.bzl imported '@bazel_tools//tools/build_defs/repo:utils.bzl', yet external/bazel_tools/tools/build_defs/repo/utils.bzl was not found, even at roots [.].
```

It's curious why utils.bzl isn't found, since it's there in the local output_base:

```
$ ls $(bazel info output_base)/external/bazel_tools/tools/build_defs/repo
android.bzl  BUILD  git.bzl  http.bzl  java.bzl  jvm.bzl  maven_rules.bzl  utils.bzl
```

Also note that `git_worker.bzl` is not there, because `git_worker.bzl` is a newly added file that isn't in any Bazel release. By referring to `@bazel_tools//...:git_worker.bzl`, Stardoc will fail to find the file.

RELNOTES: None
PiperOrigin-RevId: 254455147